#!/Users/ajtritt/anaconda3/bin/python
import sys
import urllib.request
from urllib.error import HTTPError
from urllib.parse import unquote
import re

BASE_URL = 'http://dx.doi.org/'

try:
    doi = sys.argv[1]
except IndexError:
    print('Usage: doi2bib doi [name]')
    sys.exit(1)

url = BASE_URL + doi
req = urllib.request.Request(url)
req.add_header('Accept', 'application/x-bibtex')
try:
    with urllib.request.urlopen(req) as f:
        bibtex = f.read().decode()

    S = bibtex.find('\turl')
    E = bibtex.find(',\n', S)
    bibtex = bibtex[:S] + unquote(bibtex[S:E]) + bibtex[E:]

    if len(sys.argv) > 2:
        l = list(bibtex)
        s = bibtex.find('{') + 1
        e = bibtex.find(',', s)
        l[s:e] = list(sys.argv[2])
        bibtex = "".join(l)
    print(bibtex)
except HTTPError as e:
    if e.code == 404:
        print('DOI not found.')
    else:
        print('Service unavailable.')
    sys.exit(1)
